package.json

Currently types are not linked by `package.json` and will only be available if the environment recursively pulls all `*.d.ts` in `node_modules`, which is not always the case.

fix: add types declaration to package.json

---

README.md
lib/types.ts

⚠️ breaking change
I might miss something, but can't find a reason behind this custom implementation. If there is any I would appreciate an explanation why it's needed.

Remove custom NonNullable

---

lib/types.ts
test/index.ts

As per https://github.com/krzkaczor/ts-essentials/issues/17, DeepReadonly wasn't properly recognizing a ReadonlyArray\<T> as matching any[], with the result being that such fields were wrapped in an extra DeepReadonlyObject type, which caused type clashing elsewhere. See the issue for a repro.

Add ReadonlyArray<T> check in DeepReadonly

---

README.md

For some of the types (e.g. `Omit`, `Dictionary`) they are pretty self-explanatory. But, I feel `Writable` is not. So, proposing to add a description for it to readme.

readme: add description text for `Writable`

---

package.json

Before this fix, only type definitions are exported. This fixes https://github.com/krzkaczor/ts-essentials/issues/26 .

fix(package.json): function definition not exported

---

test/index.ts

Test whether for totally writable types, apply `DeepReadonly` then `DeepWritable` will yield the original type. This is expected to be true for all totally writable types.

test: add test testDeepWritableReverseIsDeepReadonlyForTotallyWritableType

---

lib/types.ts
test/index.ts

This commit makes `unknown` assignable to `DeepReadonly<unknown>`.

Fix DeepReadonly<unknown>

---

test/index.ts

An improvement related to PR https://github.com/krzkaczor/ts-essentials/pull/33 . Add checks whether a `TotallyWritableType` is unchanged by `DeepWritable`.

test: improve testDeepWritableReverseIsDeepReadonlyForTotallyWritableType

---

lib/types.ts

`Omit` is now available in TypeScript, so I added a note about that.

Add deprecation warning to Omit

---

README.md
lib/types.ts

This is a follow-up to #59 -- I refactored the "dark magic" helper to be more readable, and added a few lines of magic explanation with a reference link, in case this needs to be updated later.

Refactor ReaadonlyKeys & WritableKeys, include helper explanation

---

README.md
example/types.ts
lib/types.ts
test/index.ts

Below is a simple example (which has been added to README)
Here is the `Teacher` interface.
```typescript
interface Teacher {
name: string,
gender: string,
students: {name: string, score: number}[]
}
```
Now suppose you want to omit `gender` property of `Teacher`, and `score` property of `students`. You can simple define a filter type and then use `DeepOmit`.
In the filter type, the properties to be omitted completely should be defined as `true`. For the properties you want to partially omit, you should recursively define the sub-properties to be omitted.
```typescript
interface Filter {
gender: true,
students: {
score: true,
}
}
type TeacherSimple = DeepOmit<Teacher, Filter>
// The result will be:
// {
//  name: string,
//  students: {name: string}[]
// }
```
NOTE: `DeepOmit` works fine …

Implement DeepOmit

---

README.md
lib/functions.ts

Because ts-essentials 3.x requires TS 3.5, we can mark the `literal` function as deprecated, to further encourage people to use the `as const` assertion instead. Adding this PR becasue I just was reminded of this in a review in my project :joy:

Deprecate the `literal` function in favor of `as const`

---

README.md
lib/types.ts
test/index.ts

It's the opposite of OmitProperties and like omit properties it isn't straight forward for most people to implement. Example from the README.md
```typescript
interface Example {
log(): void;
version: string;
versionNumber: number;
}
type ExampleOnlyMethods = PickProperties<Example, Function>;
```

implement PickProperties

---

LICENSE

According to the [`ts-essentials` README](https://github.com/krzkaczor/ts-essentials/blob/8c76e58/README.md), this project is released under the MIT license.
To avoid any doubt, it's a good practice to include an explicit LICENSE file in your project.

docs: add MIT LICENSE file

---

.vscode/settings.json
lib/types.ts
package.json
yarn.lock

All Deep-* types have been greatly simplified, including `DeepOmit`.
This PR requires TypeScript 3.7, which is a breaking change.

refactor: simplify Deep-* types via TS 3.7 recursive types (#99)

---

lib/types.ts
test/index.ts

I only implemented the change on `DeepPartial`, because current implementation of other `Deep-*` types have no problem dealing with `Array`, while the change will ruin `Tuple`.
I have also changed the related tests. @krzkaczor @quezak

[Discussion] fix: DeepPartial on Array (#112)

---

README.md
lib/types.ts
test/index.ts

Gets the XOR(Exclusive-OR) type which could make 2 types exclude each other
```typescript
type A = {a: string}
type B = {a: number; b: boolean}
type C = {c: number}
let A_XOR_B: XOR<A, B>
let A_XOR_C: XOR<A, C>
// fail
A_XOR_B = {a: 0}
A_XOR_B = {b: true}
A_XOR_B = {a: '', b: true}
A_XOR_C = {a: '', c: 0}
// ok
A_XOR_B = {a: 0, b: true}
A_XOR_B = {a: ''}
A_XOR_C = {c: 0}
```

add XOR type

---

README.md
lib/types.ts
test/index.ts

This PR introduces `SafeDictionary`. It differs from `Dictionary` in that it enforces type safety on the values. Similarly to `new Map<string, number>().get('foo')` the code `const x: SafeDictionary<number> = {}; x['foo']` is typed as `number | undefined`

Add SafeDictionary

---

lib/types.ts
test/index.ts

`SafeDictionary` is a really great recent addition, but I found out that omitting the `K` param is actually insufficient -- I'm using `Dictionary<T, number>` in multiple places, and I'd like to switch them too to the safe variant.
CC @sz-piotr since you've introduced this.

allow SafeDictionary<T, number>

---

lib/types.ts

Merge type could be simplified. This is the definition of TypeScript's built-in Extract type: 
```
type Extract<T, U> = T extends U ? T : never;
```
That's why these types are equal
```
type Test = Extract<'id' | 'name' | 'age', 'id' | 'name'>; // Equals to 'id' | 'name'
type Test2 = 'id' | 'name' // Equals 'id' | 'name'
```

Simplify Merge type

---

package.json

Rationale: improved DX -- if `dist/types.d.ts` is formatted, using a ts-essentials type you can click "go to declaration" in the editor and examine the details, without leaving your editor to check the docs etc. The currently shipped compiled version doesn't include whitespace so it's unreadable.
Drawbacks: the additional whitespace bumps the `types.d.ts` file size by ~10%.
```
0[quezak@...]~/src/ts-essentials>: ls -lh dist/*.d.ts
-rw-r--r-- 1 quezak quezak  229 03-31 11:26 dist/functions.d.ts
-rw-r--r-- 1 quezak quezak   54 03-31 11:26 dist/index.d.ts
-rw-r--r-- 1 quezak quezak 9.9K 03-31 11:26 dist/types.d.ts
0[quezak@...]~/src/ts-essentials>: yarn formatDeclarations
...
0[quezak@...]~/src/ts-essentials>: ls -lh dist/*.d.ts
-rw-r--r-- 1 quezak quezak 227 03-31 11:27 dist/functions.d.ts …
```

Proposal: format dist/*.d.ts files

---

README.md
lib/types.ts
test/index.ts

While I feel this is a typescript bug in that the compiler loses attributes on the members of a type when member names are filtered, this probably should still get worked around in ts-essentials.
The resulting DeepOmit type is not exactly the same because the members are in a different order, but I am not sure how to possibly test member ordering within Typescript.
I also made RequiredKeys and OptionalKeys exported here because I have found good utility out of them in other projects.

fix #118, keep optional flag in DeepOmit members

---

README.md
lib/types.ts
test/index.ts

Presenting:
```typescript
/** Recursive undefinable */
export type DeepUndefinable<T> = T extends Builtin
? T | undefined
: T extends Map<infer K, infer V>
? Map<DeepUndefinable<K>, DeepUndefinable<V>>
: T extends WeakMap<infer K, infer V>
? WeakMap<DeepUndefinable<K>, DeepUndefinable<V>>
: T extends Set<infer U>
? Set<DeepUndefinable<U>>
: T extends WeakSet<infer U>
? WeakSet<DeepUndefinable<U>>
: T extends Array<infer U>
? T extends IsTuple<T>
? { [K in keyof T]: DeepUndefinable<T[K]> | undefined }
: Array<DeepUndefinable<U>>
: T extends Promise<infer U>
? Promise<DeepUndefinable<U>>
: T extends {}
? { [K in keyof T]: DeepUndefinable<T[K]> }
: T | undefined;
```
This behaves exactly like `DeepNullable`, except it makes every type _undefinable_ instead of _nullable_.
Keep in mind that …

Add DeepUndefinable

---

README.md
lib/types.ts
test/index.ts

Presenting:
```typescript
type OptionalDictionary<T, K extends string | number = string> = { [key in K]?: T };
```
a weaker version of `SafeDictionary<T, K>` -- if the `K` type is **not infinite** you **do not** have to use all its union elements.
```typescript
enum MetadataKeys = {
NAME = 'NAME',
AUTHOR = 'AUTHOR',
TIMESTAMP = 'TIMESTAMP',
}
const metadata: OptionalDictionary<string, MetadataKeys> = {
AUTHOR: 'akwodkiewicz@gmail.com',
}
// whereas:
const badMetadata: SafeDictionary<string, MetadataKeys> = {
AUTHOR: 'akwodkiewicz@gmail.com',
}
/// Error:
/// Type '{ AUTHOR: string; }' is missing the following properties
/// from type 'Dictionary<string | undefined, MetadataKeys>': NAME, TIMESTAMP
```
There is no optional version of _non-safe_ `Dictionary`, because the optionality of keys …

Do not require using all SafeDictionary keys

---

lib/types.ts
test/index.ts

`ElementOf` currently reject `readonly` arrays. Wee PR to add support for same.

fix: allow readonly arrays in ElementOf

---

package.json
yarn.lock

`rm -rf` is not cross-platform, please merge this to enable windows devs to work on this repo. The `&&`, though not windows-shell-compatible, is fine because yarn specifically makes it work.

Make build script cross-platform

---

tsconfig.prod.json

Fixes #169 
I tried to set `inlineSources` first to simply change the invalid (unpublished) source file reference to an inline source and keep the whole sourcemap as a separate file, but ~despite what [the docs](https://www.typescriptlang.org/tsconfig#inlineSources) claim, this option didn't change the output,~ the same reference to `../lib` was still emitted.
Lacking a fix for that, the next step was to just inline it all into the js file.
PS: this PR is the reason for #187 and #188

Fix invalid sourcemap reference in published files

---

lib/types.ts
test/index.ts

Based on the article I wrote – https://blog.beraliv.dev/2021-05-07-opaque-type-in-typescript/
- Symbol isn't accessible (in comparison to what was before)
- Symbol exists only in types
- Works since TypeScript 2.7 – https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#unique-symbol

type: Improve Opaque

---

README.md

You don't need to cast it to `unknown` or `any` from base type to opaque
Example is provided here – https://tsplay.dev/Wy5XgW
Forgot when implemented the PR – https://github.com/krzkaczor/ts-essentials/pull/200
CC @krzkaczor

docs: 🔄 update README for Opaque type

---

.changeset/dry-squids-cross.md
lib/types.ts
test/index.ts

Fixed `DeepNullable` for `ReadonlySet` and `ReadonlyMap`

test: 🧪 DeepNullable

---

.changeset/brave-lions-confess.md
lib/types.ts
test/index.ts

Fixed `DeepUndefinable` for `ReadonlySet` and `ReadonlyMap`

test: 🧪 DeepUndefinable

---

.changeset/quick-boxes-complain.md
lib/types.ts
test/index.ts

Fix `DictionaryValues` for `SafeDictionary` with number and string literals keys

fix: 🧪 `DictionaryValues` for `SafeDictionary` with number and string literals keys

---

.changeset/bright-penguins-tap.md
lib/types.ts
test/index.ts

Fix `DeepPartial` and `Buildable` for `unknown`

fix: 🧪 DeepPartial for unknown

---

.changeset/long-bears-fetch.md
.changeset/warm-experts-cheat.md
lib/types.ts
test/index.ts

1. Allow only objects to be used in `StrictOmit`
2. `StrictOmit` returns `never` for arrays and tuples

fix: 🧪 StrictOmit

---

lib/functions.ts
test/index.ts

```ts
// the implementation
export const isExact = <U>() => <T>(object: Exact<T, U>) => {
return object;
};
// the usage
isExact<BC>()(abc);
// or possible to reuse it later (which looks nicer)
const isBC = isExact<BC>();
isBC(abc);
```
I know extra `()` is kind of annoying, but imho less annoying than `typeof obj`

suggestion: 🚀 isExact approach 2

---

.changeset/good-knives-jam.md
.changeset/strong-pillows-tease.md
README.md
package.json

fix: 🧪 Use TypeScript@^4.1.0 because of introduced recursive conditional types

---

package.json
yarn.lock

Test version against at least TypeScript@4.1.0 (as we use features from this version)

build: 📦 use typescript@^4.1.0 in devDependencies 

---

.changeset/neat-impalas-beam.md
lib/types.ts

fix: 🧪 tolerate keyofStringsOnly option in TypeScript

---

.changeset/five-olives-reply.md
lib/types.ts

Related to #281
I'm still thinking what can be the reason
I'm also thinking to add CI checks for all the versions that we support (currently 4.1 and newer)

fix: 🧪 DeepPick & DeepOmit starting from TypeScript 4.5

---

README.md
lib/types.ts
test/predicate-type.ts

Fixes #253
1. Adds type called `PredicateType` to support snagging predicates off of guarded functions
2. Adds utility type called `PredicateFunction` to let folks duplicate the interface for things like the `isArrayOf` [example in the tests](https://github.com/ts-essentials/ts-essentials/blob/3fddc463985967e6084a9a7e0d5009b15d6ef793/test/predicate-type.ts#L36). I left it undocumented on the readme because this doesn't seem like a normal thing to need, but it is easily discovered

add PredicateType and PredicateFunction interfaces and full set of tests

---

README.md

miss `[]` in DeepPick/DeepOmit example
before
this pr

docs: type error in DeepPick/DeepOmit example

---

.all-contributorsrc
.changeset/early-cars-approve.md
README.md
lib/types.ts
test/index.ts

**Changes:**
* add new `NonEmptyArray` type
* add missing readme menu entry for `NonEmptyObject` type
Resolves https://github.com/ts-essentials/ts-essentials/issues/307

feat: add NonEmptyArray type

---

.github/workflows/release.yml

Change `changesets/action@master` to `changesets/action@main`
The workflow file using `changesets/action` is currently using `@master` as the version. This branch has been frozen and deprecated. Please update your workflow to either use `@v1` or a specific commit SHA that is tagged.
It's a warning in Version Packages
Logs – https://github.com/ts-essentials/ts-essentials/runs/7185388057?check_suite_focus=true

ci: 🧪 fix changesets from master to main

---

.github/workflows/release.yml

Change `changesets/action@main` to `changesets/action@v1`
The workflow file using `changesets/action` is currently using `@master` as the version. This branch has been frozen and deprecated. Please update your workflow to either use `@v1` or a specific commit SHA that is tagged.
It's a warning in Version Packages – https://github.com/ts-essentials/ts-essentials/runs/7185388057?check_suite_focus=true
Switching to `main` isn't supported – https://github.com/ts-essentials/ts-essentials/runs/7185463113?check_suite_focus=true

ci: 🧪 fix changesets from main to v1

---

.changeset/moody-oranges-care.md
lib/types.ts
test/index.ts

**Changes:**
- fix DeepReadonly for a union with an array of itself
Resolves #306

fix: DeepReadonly for a union with an array of itself (#306)

---

.changeset/nasty-plants-check.md
lib/types.ts
test/index.ts
test/mark-optional.ts
test/mark-readonly.ts
test/mark-required.ts
test/mark-writable.ts

Add union support to all Mark* methods: `MarkRequired`, `MarkOptional`, `MarkReadonly` and `MarkWritable`
Fix introduced bug – https://github.com/ts-essentials/ts-essentials/issues/323
Codesandbox fix – https://codesandbox.io/s/type-guard-error-forked-dyllt8?file=/src/App.tsx

feat: ➕ add union support for Mark* methods

---

.changeset/friendly-walls-hope.md
lib/types.ts

Refactored the older function signature to variadic tuple type introduced in TS 4.0

refactor(tail): use variadic tuple type

---

.changeset/nice-beans-lick.md
README.md
lib/functions.ts
test/create-factory-with-constraint.ts
test/index.ts
test/is-exact.ts

Adds `createFactoryWithConstraint`
It's helpful when you need to restrict the function argument with generic constraint, but also narrow the value within this generic constraint
Related to https://github.com/ts-essentials/ts-essentials/issues/317

feat: ➕ add createFactoryWithConstraint

---

README.md

Include `Pick` in README.md
So you will see that it's already strict and you don't need your own implementation, e.g. `StrictPick`
Related to #311

docs: 📄 include Pick

---

.changeset/two-worms-agree.md
.github/workflows/typecheck.yml
README.md
lib/literal-types/README.md
test/strict-extract.ts
test/ts-version.ts
yarn.lock

1. Replace `Result:` with `^?` comments
2. Update `HouseAnimalWithStrictExtract` example for `StrictExtract` since version 4.6 and higher
3. Add more CI checks for newer TypeScript versions
4. Use typescript@4.7.x locally
1. It looks more familiar for TypeScript community
2. Example in README leads to TypeError now
3. To be able to keep README up-to-date
4. To be able to see changes in the codebase

docs: update README comments

---

.changeset/rare-forks-deliver.md
lib/types.ts
test/value-of.ts

Added the basic test coverage for `ValueOf<T>`.
@Beraliv Feel free to add more test cases or if we need to check the behavior for other edge cases as well. 
fixes #333

Improve the Output range and cover edge cases for `ValueOf<T>` type

---

.changeset/great-hounds-brush.md
lib/types.ts
test/index.ts
test/non-empty-object.ts

fixed #335 
@Beraliv 
Have also added the additional test cases for the improved constraint!

fix the object constraint for `NonEmptyObject<T>`

---

.github/ISSUE_TEMPLATE.md
.github/pull_request_template.md

It introduces PR template for all contributors to fill
Other changes:
- Added default issue template to warn contributors to use existing templates
It will help to validate that people are reading [Contributing](https://github.com/ts-essentials/ts-essentials/blob/master/CONTRIBUTING.md) guide and linking PRs to existing issues

ci: 🔄 Use default issue and PR template

---

.changeset/early-students-brush.md
README.md
package.json

This marks `typescript` as optional so that JS-only apps may import code from libraries dependent upon ts-essentials without having to install TypeScript.
The version constraint for consumers using `typescript` would still apply.

chore(deps): mark typescript as optional

---

.changeset/weak-llamas-lick.md
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/typecheck.yml
lib/camel-case/index.ts

- Added TypeScript 5.0, 5.1 & 5.2 to CI for typecheck
- Used node 14 on CI
- Fix regression in TypeScript 5.1 with CamelCase (iteration step was infinite because of taking a substring as empty string)

ci: ➕ Add compatibility versions of 5.0, 5.1 and 5.2 typescript versions

---

.changeset/silly-buses-camp.md
lib/deep-required/index.ts
test/deep-required.ts

Work-in-progress attempt to fix #366. See comments inline.

fix: support types extending Array in DeepRequired

---

lib/omit-properties/index.ts
lib/pick-keys-by-value.ts
lib/pick-keys/index.ts
lib/pick-properties/index.ts
test/pick-keys.ts

I took advantage of [key remapping](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types) feature introduced starting from Typescript 4.1.
This allows to reduce the number of iterations when these types are used and to remove the utility PickKeysByValue.
In tests, the "wtf" cases continue to be a bit "wtf" but they are closer to be keys, at least.
I wanted to use this syntax for other cases, but it changes the behavior a bit more and, despite I think it would be reasonable the new behavior, it requires more discussion.

Use key remapping from Typescript 4.1 for PickProperties and OmitProperties

---

.changeset/rich-badgers-learn.md
.prettierignore
README.md
example/types.ts
lib/dictionary-values/README.md
lib/dictionary-values/index.ts
lib/value-of/README.md
test/index.ts
test/value-of.ts

- Deprecated `DictionaryValues`
- Removed `DictionaryValues` from docs
- Move unit tests to `ValueOf`

feat: deprecate DictionaryValues

---

.changeset/pretty-boats-suffer.md
lib/create-type-options.ts
lib/paths/index.ts
test/create-type-options.ts
test/paths.ts

- Improve `Paths` performance by limiting the depth of paths to 7 (default)
- Added `UserOptions` config, managed by `CreateTypeOptions`
- Covered `UserOptions` and `Paths` by unit tests (added test cases for depths and circular references)

perf: Improve Paths

---

.changeset/slow-dolphins-fetch.md
lib/paths/README.md
lib/paths/index.ts
test/paths.ts

- resolves: #411
Adds optional configuration that allows wildcards to satisfy array index access.

feat(Paths): Add optional `anyArrayIndexAccessor`

---

.changeset/ninety-forks-poke.md
lib/optional-keys/index.ts
test/index.ts

Currently, the `OptionalKeys` type doesn’t handle primitives and arrays as expected.
Since `OptionalKeys` is a [homomorphic mapped type](https://github.com/microsoft/TypeScript/pull/26063), so when it’s instantiated with a primitive `Type`, it simply returns back `Type`. As a result, instantiating `OptionalKeys` with `string` yields `string[keyof string]`, which isn’t the intended result.
The fix here is straightforward, we simply bypass primitives by changing the conditional from `Type extends unknown` to `Type extends object`. So, when `OptionalKeys` is instantiated with primitives, the condition evaluates to false, returning `never` as expected.
Ideally, `OptionalKeys<[1, 2?]>` should return `"1"`, but instead, it returns a bunch of unintended things.
Here's the existing code for …

Fix: Behaviour of `OptionalKeys` when instantiated with primitives and arrays

---

package.json

@Beraliv Here's a tiny PR.
Just realised that the `test:fix` script now fails because it doesn’t update `tsconfig.test.json`. This update is now required since even the locked TypeScript version (i.e., `4.9.5`) needs a few files to be excluded due to the changes made in [this PR](https://github.com/ts-essentials/ts-essentials/pull/416).
I've removed running tests from the `test:fix` script in this PR. However, if you feel we should not remove it, then we could do it like this:
```diff
- "test:fix": "prettier --write {bench,lib,test}/**/*.ts && tsc --project tsconfig.test.json --outDir ./testDist && rimraf ./testDist"
+ "test:fix": "prettier --write {bench,lib,test}/**/*.ts && yarn test"
```
<br />
And either ways, I think we should probably rename the script to `prettier:fix` because the …

Fix: Failing `test:fix` script

---

.changeset/heavy-gorillas-march.md
lib/mark-optional/index.ts
lib/mark-readonly/index.ts
test/mark-optional.ts
test/mark-required.ts

Currently, generic instantiations of `MarkOptional` are not assignable to `Partial`. But I don't see a reason why it shouldn't.
<br />
<br />
This PR:
1. Refactors the implementation of `MarkOptional` to make it assignable to `Partial`.
2. Adds some more test cases for `MarkReadonly`.

Fix: Make `MarkOptional<Type, Keys extends keyof Type>` assignable to `Partial<Type>`

---

.changeset/orange-cycles-wink.md
lib/mark-required/index.ts
lib/mark-writable/index.ts
test/mark-optional.ts
test/mark-readonly.ts
test/mark-required.ts
test/mark-writable.ts

The `MarkRequired` and `MarkWritable` types currently have issues when the second type argument is `any`. This is because their implementation relies on `Pick`, which does not handle `any` correctly.
For eg, `MarkRequired<{ a?: 1; b?: 2 }, any>` currently evaluates to type `{ [x: string]: any; a?: 1; b?: 2 }`, instead it should have simply evaluated to type `{ a: 1; b: 2 }`.
This PR refactors these types to use a combination of `Omit` and `Exclude` instead of `Pick`, ensuring proper functionality with `any`.

Fix: `MarkRequired` and `MarkWritable` types when `Keys` is `any`

---

.changeset/breezy-ads-punch.md
CONVENTIONS.md
README.md
lib/index.ts
lib/non-union/README.md
lib/non-union/index.ts
test/non-union.ts

1. Added `NonUnion` utility type, with its README and tests
2. Included `NonEmptyArray` suggestion in CONVENTIONS.md

feat: 🚀 Add `NonUnion` utility type

---

.changeset/curly-poets-battle.md
lib/mark-optional/index.ts
lib/prettify/index.ts
test/prettify.ts

This PR implements the changes mentioned in https://github.com/ts-essentials/ts-essentials/issues/439#issuecomment-3195857140.

fix: `Prettify` when instantiated with classes containing private/protected members

---

.changeset/tender-lamps-join.md
.changeset/twelve-suns-fly.md
lib/union-keys/index.ts
lib/union-to-intersection/index.ts
lib/union-to-tuple.ts
test/deep-mark-optional.ts
test/union-keys.ts
test/union-to-intersection.ts

1. Fixed assignability for `UnionKeys` and `UnionToIntersection`
2. Added unit tests for `UnionKeys` and `UnionToIntersection` assignability
3. Referenced the hack from https://github.com/sindresorhus/type-fest/pull/1009
4. Used non-assignable version of `UnionToIntersection` in `UnionToTuple`
@som-sm thank you a lot for flagging the issue in https://github.com/ts-essentials/ts-essentials/pull/449/files#r2404512712 and coming up with the workaround in https://github.com/sindresorhus/type-fest/pull/1009 🧡

fix: `UnionKeys` assignability
