ts-essentials/ts-essentials

README.md, lib/types.ts
This PR adds a type which extracts types from object values - nothing ground breaking, it just makes commonly written typespecs a bit more concise.
=> Add ValueOf type

README.md, lib/types.ts, test/index.ts
Closes #45 
Named the type `MarkRequired` after discussion.
=> Add MarkRequired type

lib/types.ts, test/index.ts
=> fix: check Primitive in DeepPartial (#19)

lib/types.ts
This PR is as the title describes.
=> feat: add bigint and symbol to Primitive (#63)

README.md, example/types.ts, lib/types.ts, package.json, test/index.ts, yarn.lock
- Refactor DeepReadonly, DeepWritable, DeepPartial
- Implement DeepNonNullably
- Refactor and add related tests
This refactor should solve #14 #40 
And since all Deep types are very similar now, it provides a foundation for #12
=> A complete refactor to Deep* types

lib/types.ts
=> Add Function as a check before object to prevent #73

README.md, lib/types.ts, test/index.ts
=> implement NonEmptyObject

lib/types.ts
=> Refactor: cleanup Deep* types (#92)

README.md, lib/types.ts, test/index.ts
Implemented @kalbert312 proposal mentioned in #77, because I needed it in my project.
=> Implement MarkOptional

README.md, lib/functions.ts, test/index.ts
Closes https://github.com/krzkaczor/ts-essentials/issues/106
=> Add assertion functions

README.md
Closes https://github.com/krzkaczor/ts-essentials/issues/102
=> Improve docs by adding alliasses for some types

lib/types.ts, test/index.ts
=> feat: Deep-* support for WeakMap/WeakSet/Promise/Error/RegExp

README.md, lib/functions.ts, test/index.ts
=> #135: add noop

README.md, lib/types.ts, test/index.ts
Closes https://github.com/krzkaczor/ts-essentials/issues/87
=> Add Exact type

README.md, lib/types.ts, test/index.ts
=> Add ElementOf

README.md, example/types.ts, lib/types.ts, test/index.ts
Closes: https://github.com/krzkaczor/ts-essentials/issues/110
Closes: https://github.com/krzkaczor/ts-essentials/issues/158
It's a breaking change, will be released as 7.0.0
=> Redo opaque, add Awaited, AsyncOrSyncType and Newable

README.md
Suggest adding `ts-essentials` as a runtime dependency when using functions
=> Fixes #172

README.md, lib/types.ts, test/index.ts
time to time I need to accept keys as parameters of a function which match only specific types in original object.
=> feat: PickKeys

lib/types.ts, test/index.ts
TODO: remove after merge of https://github.com/krzkaczor/ts-essentials/pull/200
=> type: All tests before opaque improvement

README.md, lib/types.ts, package.json, test/index.ts, yarn.lock
=> feat: ➕ add MergeN

lib/types.ts, test/index.ts
Fixes: https://github.com/krzkaczor/ts-essentials/issues/197
=> DeepReadonly support for the 'unknown' type

README.md
@krzkaczor next release version should be 4.0 I guess, right?
=> docs: 🔄 update README for typescript@^4.0.0

.changeset/dirty-points-cry.md, README.md, lib/types.ts, test/index.ts
=> feat: ➕ add StrictExtract

.changeset/kind-moose-reflect.md, .changeset/moody-berries-wonder.md, .changeset/quiet-coats-lay.md, .changeset/stale-eggs-camp.md, .changeset/twelve-tools-happen.md
The description is missed for next PRs:
- https://github.com/krzkaczor/ts-essentials/pull/210
- https://github.com/krzkaczor/ts-essentials/pull/213
- https://github.com/krzkaczor/ts-essentials/pull/198
=> docs: 🔄 changeset update 📄

README.md
=> docs: ➕ add strictNullChecks 📄

.changeset/healthy-carrots-shake.md, README.md, lib/types.ts, test/index.ts
=> feat: 🚀 IsUnknown

.changeset/four-paws-sparkle.md, lib/types.ts, test/const.ts, test/deep-omit.ts, test/deep-pick.ts, test/index.ts
=> feat: 🔄 update DeepOmit

.changeset/cold-poets-dream.md, lib/types.ts, test/deep-omit.ts, test/deep-pick.ts
=> fix: 🧪 DeepPick & DeepOmit for set, map, promise and array

.changeset/cold-poets-dream.md, .changeset/four-paws-sparkle.md, .changeset/fresh-ladybugs-hug.md, .changeset/good-chefs-hope.md, .changeset/sweet-ravens-tease.md, .changeset/ten-tigers-shop.md, .changeset/twenty-clouds-ring.md, CHANGELOG.md, package.json
This reverts commit 44fab53d1102f3861d802f0ba3d5a1f8bc2c16e2.
=> release: Revert "Version Packages (#264)"

lib/types.ts
To be able to fix https://github.com/krzkaczor/ts-essentials/runs/4487785011?check_suite_focus=true for the release merge – https://github.com/krzkaczor/ts-essentials/pull/264
=> refactor: ❌ remove test/types from build

.changeset/shiny-ads-carry.md, .github/workflows/typecheck.yml, package.json
=> fix: 🧪 skip setting TsVersion on postinstall

lib/types.ts, test/index.ts, test/mark-required.ts
=> fix: 🧪 MarkRequired: Exclude => Omit

test/index.ts, test/strict-omit.ts
More explanation about the possible issue – https://twitter.com/beraliv/status/1486681264056901637
=> test: 🧪 StrictOmit checks for unions

.changeset/fluffy-seas-thank.md, lib/types.ts, test/index.ts, test/readonly-array-or-single.ts
Please review and merge. Thanks.
=> feat: Add `ReadonlyArrayOrSingle` which is a counterpart to `ArrayOrSingle` with the array being readonly

.github/ISSUE_TEMPLATE/01-bug-report.yaml, .github/ISSUE_TEMPLATE/02-enhancement.yaml
- Added bug report issue template
- Added enhancement issue template
To improve DX
=> docs: ➕ add issue template 📄

.github/ISSUE_TEMPLATE/01-bug-report.yaml, .github/ISSUE_TEMPLATE/02-enhancement.yaml
- Replaced "Why" with"Examples"
- Updated TS Playground title and link
Improved DX
=> docs: 🔄 update issue template 📄

.changeset/hip-papayas-live.md, CONTRIBUTING.md, CONVENTIONS.md
- Added naming to list of conventions
=> docs: 📄 Introduce conventions

.github/workflows/ci.yml, README.md, package.json, yarn.lock
Non-functional change, aiming to remove Codechecks due to failures on CI.
=> refactor: Remove Codechecks
